export const HOME_VIEW = 'HOME_VIEW'
export const INSTRUCTIONS_VIEW = 'INSTRUCTIONS_VIEW'
export const DISTRICT_VIEW = 'DISTRICT_VIEW'
export const SCANNING_VIEW = 'SCANNING_VIEW'
export const WEIGHT_VIEW = 'WEIGHT_VIEW'
export const CONGRATS_VIEW = 'CONGRATS_VIEW'
export const FAIL_VIEW = 'CONGRATS_VIEW'
export const GMINA_VIEW = 'GMINA_VIEW'
export const LOGIN_VIEW = 'LOGIN_VIEW'
export const MULTI_CHOICE_VIEW = 'MULTI_CHOICE_VIEW'


